import {useEffect,useRef,useState} from 'react';
import {api,errorMessage,isUnauthorized} from './api';
import {Feedback,Modal} from './ui';
import {useLanguage} from './i18n';
import {useTimezone} from './time';
import {announceRecordingCleanup,bytes,confirmationReady,instantChoice,pageSelection} from './cleanup';
import type {Criteria,Preview,Progress,Recording} from './cleanup';

export function RecordingCleanup({onError}:{onError:(value:unknown)=>void}){
  const {t,when}=useLanguage(),zone=useTimezone();
  const [cameras,setCameras]=useState<{id:number;name:string}[]>([]),[ids,setIds]=useState<number[]>([]),[all,setAll]=useState(true);
  const [custom,setCustom]=useState(false),[start,setStart]=useState(''),[end,setEnd]=useState(''),[startFold,setStartFold]=useState(''),[endFold,setEndFold]=useState('');
  const [criteria,setCriteria]=useState<Criteria>({}),[rows,setRows]=useState<Recording[]>([]),[total,setTotal]=useState(0),[offset,setOffset]=useState(0),[selected,setSelected]=useState<number[]>([]);
  const [preview,setPreview]=useState<Preview|null>(null),[text,setText]=useState(''),[token,setToken]=useState(''),[progress,setProgress]=useState<Progress|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState<unknown>('');
  const generation=useRef(0),filterKey=JSON.stringify([all,ids,custom,start,end,startFold,endFold,zone]);
  const [appliedKey,setAppliedKey]=useState(filterKey);
  const dirty=filterKey!==appliedKey,running=!!token&&progress?.state!=='done';
  function fail(e:unknown){setError(e);if(isUnauthorized(e))onError(e)}
  async function list(value:Criteria,page=0){const version=++generation.current;setBusy(true);setError('');try{const result=await api<{total:number;recordings:Recording[]}>(`/api/recordings/cleanup/query?offset=${page}`,{method:'POST',body:JSON.stringify(value)});if(version===generation.current){setRows(result.recordings);setTotal(result.total);setOffset(page);setCriteria(value);return true}}catch(e){if(version===generation.current)fail(e)}finally{if(version===generation.current)setBusy(false)}}
  useEffect(()=>{api<typeof cameras>('/api/cameras').then(setCameras).catch(fail);list({});return()=>{generation.current++}},[]);
  useEffect(()=>{setPreview(null);setText('');setSelected([])},[filterKey]);
  useEffect(()=>{
    if(!token)return;
    let live=true,timer:ReturnType<typeof setTimeout>;
    async function poll(){try{const result=await api<Progress>(`/api/recordings/cleanup/progress/${token}`);if(!live)return;setProgress(result);if(result.state==='done'){if(result.deleted||result.missing||result.failed)announceRecordingCleanup();setSelected([]);await list(criteria,0)}else timer=setTimeout(poll,500)}catch(e){if(live){fail(e);timer=setTimeout(poll,2000)}}}
    poll();return()=>{live=false;clearTimeout(timer)};
  },[token]);
  async function resolve(local:string,fold:string){if(!local)throw new Error(t('Choose both date and time boundaries.'));const [date,time]=local.split('T');const response=await api<{instants:{time:string}[]}>('/api/time/resolve',{method:'POST',body:JSON.stringify({date,time})});return instantChoice(response.instants,fold)}
  async function apply(){setBusy(true);try{if(!all&&!ids.length)throw new Error(t('Select at least one camera.'));const value:Criteria=all?{}:{camera_ids:ids};if(custom){value.start=await resolve(start,startFold);value.end=await resolve(end,endFold);if(Date.parse(value.start)>=Date.parse(value.end))throw new Error(t('Start must precede end.'))}setSelected([]);if(await list(value))setAppliedKey(filterKey)}catch(e){fail(e)}finally{setBusy(false)}}
  async function review(individual:boolean){setBusy(true);setError('');try{const result=await api<Preview>('/api/recordings/cleanup/preview',{method:'POST',body:JSON.stringify(individual?{...criteria,recording_ids:selected}:criteria)});setText('');setPreview(result)}catch(e){fail(e)}finally{setBusy(false)}}
  async function remove(){if(!preview||!confirmationReady(preview,text))return;setBusy(true);try{const result=await api<{token:string}>('/api/recordings/cleanup/delete',{method:'POST',body:JSON.stringify({token:preview.token,confirmation:preview.clear_all?text:'confirm'})});setToken(result.token);setProgress(null);setPreview(null)}catch(e){fail(e)}finally{setBusy(false)}}
  const name=(id:number)=>cameras.find(camera=>camera.id===id)?.name||`${t('Camera')} ${id}`;
  return <section className="recording-cleanup"><h3>{t('Manage recordings / Storage cleanup')}</h3>
    <fieldset disabled={busy||running}><legend>{t('Cleanup scope')}</legend><label><input type="checkbox" checked={all} onChange={e=>setAll(e.target.checked)}/>{t('All cameras')}</label>{!all&&cameras.map(camera=><label key={camera.id}><input type="checkbox" checked={ids.includes(camera.id)} onChange={e=>setIds(current=>e.target.checked?[...current,camera.id]:current.filter(id=>id!==camera.id))}/>{camera.name}</label>)}</fieldset>
    <fieldset disabled={busy||running}><legend>{t('Time range')} ({zone})</legend><label><input type="checkbox" checked={custom} onChange={e=>setCustom(e.target.checked)}/>{t('Custom date/time range')}</label>{!custom&&<span>{t('All time')}</span>}{custom&&<div className="toolbar">{[['Start',start,setStart,startFold,setStartFold],['End',end,setEnd,endFold,setEndFold]].map(([label,value,setValue,fold,setFold])=><label key={String(label)}>{t(String(label))}<input type="datetime-local" value={String(value)} onChange={e=>(setValue as (v:string)=>void)(e.target.value)}/><select aria-label={`${label} repeated time`} value={String(fold)} onChange={e=>(setFold as (v:string)=>void)(e.target.value)}><option value="">{t('If time repeats, choose occurrence')}</option><option value="earlier">{t('Earlier occurrence')}</option><option value="later">{t('Later occurrence')}</option></select></label>)}</div>}</fieldset>
    <div className="toolbar"><button disabled={busy||running} onClick={apply}>{t('Apply filters')}</button><button disabled={busy||running||dirty||!total} onClick={()=>review(false)}>{t('Preview cleanup of all filtered recordings')}</button><button disabled={busy||running||dirty||!selected.length} onClick={()=>review(true)}>{t('Preview selected recordings')} ({selected.length})</button></div>
    {dirty&&<Feedback>{t('Apply filters to refresh the list before previewing cleanup.')}</Feedback>}{!!error&&<Feedback tone="bad">{errorMessage(error)}</Feedback>}{busy&&<Feedback>{t('Loading…')}</Feedback>}
    <p>{t('Recordings')}: {total} · {t('Selected')}: {selected.length}. {t('Select all applies only to this page (100 recordings). Selections persist across pages and reset when filters change.')}</p>
    <div className="toolbar"><button disabled={busy||running||dirty} onClick={()=>setSelected(pageSelection(rows,selected,true))}>{t('Select all on this page')}</button><button disabled={busy||running} onClick={()=>setSelected([])}>{t('Deselect all')}</button></div>
    {!busy&&!rows.length&&<Feedback>{t('No recordings match these filters.')}</Feedback>}
    <div className="cleanup-table"><table><thead><tr>{['Select','Camera','Start','End','Duration','File size'].map(label=><th key={label}>{t(label)}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><input aria-label={`${t('Select recording')} ${row.id}`} type="checkbox" disabled={busy||running||dirty} checked={selected.includes(row.id)} onChange={e=>setSelected(pageSelection([row],selected,e.target.checked))}/></td><td>{name(row.camera_id)}</td><td>{when(row.started_at)}</td><td>{when(row.ended_at)}</td><td>{Math.round((Date.parse(row.ended_at)-Date.parse(row.started_at))/1000)} s</td><td>{bytes(row.size_bytes)}</td></tr>)}</tbody></table></div>
    <div className="toolbar"><button disabled={busy||running||dirty||offset===0} onClick={()=>list(criteria,offset-100)}>{t('Previous')}</button><span>{rows.length?offset+1:0}–{offset+rows.length} / {total}</span><button disabled={busy||running||dirty||offset+rows.length>=total} onClick={()=>list(criteria,offset+100)}>{t('Next')}</button></div>
    {progress&&<Feedback tone={progress.failed?'warning':progress.state==='done'?'good':'neutral'}>{t(progress.state==='done'?'Cleanup complete':'Deleting recordings…')} {progress.processed} / {progress.total} · {t('Deleted')}: {progress.deleted} · {t('Reclaimed space')}: {bytes(progress.reclaimed_bytes)} · {t('Skipped active')}: {progress.active} · {t('Already missing')}: {progress.missing} · {t('Failed')}: {progress.failed}</Feedback>}
    {preview&&<Modal title={t('Storage cleanup preview')} closeLabel={t('Cancel')} onClose={()=>{if(!busy)setPreview(null)}}><p>{t('Cameras')}: {preview.cameras.map(name).join(', ')||'—'}</p><p>{t('Period')}: {preview.criteria.start&&preview.criteria.end?`${when(preview.criteria.start)} – ${when(preview.criteria.end)}`:t('All time')}</p><p>{t('Recordings found')}: {preview.count} · {t('Space to reclaim')}: {bytes(preview.size_bytes)}</p><p>{t('Active recording files are excluded')}: {preview.active_excluded}</p>{!!preview.not_found&&<Feedback>{t('Requested recordings no longer indexed')}: {preview.not_found}</Feedback>}<Feedback tone="warning">{t('Whole segments overlapping the selected interval [start, end) will be deleted, including footage outside its boundaries. Files that become active are skipped at execution. This action cannot be undone.')}</Feedback>{preview.clear_all&&<label>{t('Type DELETE to clear all recordings')}<input aria-label={t('Type DELETE')} value={text} onChange={e=>setText(e.target.value)}/></label>}<div className="toolbar"><button disabled={busy} onClick={()=>setPreview(null)}>{t('Cancel')}</button><button className="danger" disabled={busy||!confirmationReady(preview,text)} onClick={remove}>{t('Delete recordings')} ({preview.count})</button></div></Modal>}
  </section>;
}
